version: '3.8'
services:
  dev-db:
    image: postgres
    ports:
    - 8080:8080
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: nest
    networks:
      - testnetwork
networks:
  testnetwork: